<?php

/**
 * @file
 * Module implementation file.
 */

/**
 * Implements hook_xautoload()
 *
 * Register additional classes, namespaces, autoload patterns, that are not
 * already registered by default.
 *
 * @param \Drupal\xautoload\Adapter\LocalDirectoryAdapter $adapter
 *   An adapter object that can register stuff into the class loader.
 */
function plug_xautoload($adapter) {
  // Register a namespace with PSR-4.
  $adapter->addPsr4(
  // The namespace.
    'Drupal\Core\\',
    // Path to the PSR-4 base directory.
    'src/Core'
  );
}
