<?php

/**
 * @file
 * Module implementation file.
 */

/**
 * Implements hook_menu().
 */
function plugs_example_menu() {
  $items['plugs/test'] = array(
    'title' => 'Plugins example',
    'description' => 'Plugins example page.',
    'page callback' => 'plugs_example_test_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Page callback to test the plugins.
 */
function plugs_example_test_page() {
  // TODO: This $namespaces array should be generated automagically.
  $namespaces = new \ArrayObject(array(
    'Drupal\plugins_example' => drupal_get_path('module', 'plugins_example') . '/src',
  ));
  $manager = new Drupal\plugins_example\NamePluginManager($namespaces, new \DrupalDatabaseCache('name'));
  $output = array();
  foreach ($manager->getDefinitions() as $id => $plugin) {
    // This is just a silly way to show how you can pass arbitrary configuration
    // at runtime. If true, the name will be wrapped in <em></em>.
    $random_bool = (bool) floor(mt_rand(0, 2));
    $output[] = $manager->createInstance($id, array('em' => $random_bool))->displayName();
  }
  return implode(', ', $output);
}
